name: Build and Deploy

on:
  release:
    types: [published]
    branches: [main, release]

env:
  PLUGIN_SLUG: airyseo
  PLUGIN_FILE: airyseo.php

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate version and decide publish
        id: validate
        uses: airygen/actions/validate-plugin-version@main
        with:
          plugin_file: ${{ env.PLUGIN_FILE }}

      - name: Build
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Verify vendor folder
        run: |
          if [ ! -d vendor ]; then
            echo "vendor/ was not generated. Check Composer logs and PHP platform constraints."
            exit 1
          fi

      - name: Stage & Zip
        id: pack
        uses: airygen/actions/stage-zip-file@main
        with:
          plugin_file: ${{ env.PLUGIN_FILE }}
          plugin_slug: ${{ env.PLUGIN_SLUG }}
          plugin_version: ${{ steps.validate.outputs.tag }}
          stage_dirs: |
            languages
            resources
            inc
            src
            vendor
          extra_files: |
            uninstall.php
            LICENSE
            composer.json
  
      - name: Attach zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.pack.outputs.zip_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Deploy to WordPress.org
        if: steps.validate.outputs.publish == 'true' && github.event.release.target_commitish == 'release'
        uses: 10up/action-wordpress-plugin-deploy@2.3.0
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USER }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASS }}
        with:
          slug: ${{ env.PLUGIN_SLUG }}
          build-dir: ${{ steps.pack.outputs.release_dir }}
          generate-zip: true
